In [1]:
pwd

'C:\\Users\\rajpoot'

In [2]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt



In [3]:
df=pd.read_csv("C:/Data Files/SVM/Movie_classification.csv" , header=0)

In [4]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           494 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

# Missing value Imputation

In [6]:
df["Time_taken"].mean()

157.3914979757085

In [7]:
df["Time_taken"].fillna(value = df["Time_taken"].mean() , inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Marketing expense    506 non-null    float64
 1   Production expense   506 non-null    float64
 2   Multiplex coverage   506 non-null    float64
 3   Budget               506 non-null    float64
 4   Movie_length         506 non-null    float64
 5   Lead_ Actor_Rating   506 non-null    float64
 6   Lead_Actress_rating  506 non-null    float64
 7   Director_rating      506 non-null    float64
 8   Producer_rating      506 non-null    float64
 9   Critic_rating        506 non-null    float64
 10  Trailer_views        506 non-null    int64  
 11  3D_available         506 non-null    object 
 12  Time_taken           506 non-null    float64
 13  Twitter_hastags      506 non-null    float64
 14  Genre                506 non-null    object 
 15  Avg_age_actors       506 non-null    int

# Dummy Variables 

In [9]:
df = pd.get_dummies(df,columns=["3D_available" , "Genre"] , drop_first = True)

In [10]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  ...  Time_taken  Twitter_hastags  \
0            7.995           7.94  ...      109.60          223.840   
1            7.470           7.44  ...      146.64          243.456   
2            7.515           7.44  ...      147.88         2022.400   
3            7.020           8.26  ...      185.36          225.344   
4            7.070           8.26  ...      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  Start_Tech_Oscar  \
0              23            494       48000                 1   
1              42            462       43200                 0   
2              38            458       69400                 1   
3              45            472       66800                 1   
4              55            395       72400                 1   

   3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0                 1             0            0               1  
1                 0             0            1               0  
2                 0             1            0               0  
3                 1             0            1               0  
4                 0             0            1               0  

[5 rows x 21 columns]

# X-Y Split

In [11]:
X = df.loc[: , df.columns!="Start_Tech_Oscar"]
type(X)

pandas.core.frame.DataFrame

In [12]:
X.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   
2            7.515           7.44         547051      147.88         2022.400   
3            7.020           8.26         516279      185.36          225.344   
4            7.070           8.26         531448      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  3D_available_YES  Genre_Comedy  \
0              23            494       48000                 1             0   
1              42            462       43200                 0             0   
2              38            458       69400                 0             1   
3              45            472       66800                 1             0   
4              55            395       72400                 0             0   

   Genre_Drama  Genre_Thriller  
0            0               1  
1            1               0  
2            0               0  
3            1               0  
4            1               0

In [13]:
X.shape

(506, 20)

In [14]:
y=df["Start_Tech_Oscar"]

In [15]:
type(y)

pandas.core.series.Series

In [16]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Start_Tech_Oscar, dtype: int64

In [17]:
y.shape

(506,)

# Train-Test Split

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train , X_test , y_train , y_test =train_test_split(X,y,test_size=0.2,random_state=0)

In [20]:
X_train.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
220            27.1618               67.40               0.493  38612.805   
71             23.1752               76.62               0.587  33113.355   
240            22.2658               64.86               0.572  38312.835   
6              21.7658               70.74               0.476  33396.660   
417           538.8120               91.20               0.321  29463.720   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
220         162.0               8.485                8.640            8.485   
71           91.0               7.280                7.400            7.290   
240         127.8               6.755                6.935            6.800   
6           140.1               7.065                7.265            7.150   
417         162.6               9.135                9.305            9.095   

     Producer_rating  Critic_rating  Trailer_views  Time_taken  \
220            8.670           8.52         480270      174.68   
71             7.455           8.16         491978      200.68   
240            6.840           8.68         470107      204.80   
6              7.400           8.96         459241      139.16   
417            9.165           6.96         302776      172.16   

     Twitter_hastags  Avg_age_actors  Num_multiplex  Collection  \
220          224.272              23            536       53400   
71           263.472              46            400       43400   
240          224.320              24            387       54000   
6            243.664              41            522       45800   
417          301.664              60            589       20800   

     3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
220                 0             0            0               1  
71                  0             0            0               0  
240                 1             1            0               0  
6                   1             0            0               1  
417                 1             0            0               0

In [21]:
X_train.shape

(404, 20)

In [22]:
y_train.head()

220    1
71     1
240    1
6      0
417    1
Name: Start_Tech_Oscar, dtype: int64

In [23]:
X_test.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
329            21.3448               61.48               0.540  35179.815   
371           204.6460               91.20               0.369  34529.880   
219            22.2850               82.78               0.450  35402.015   
403           516.0340               91.20               0.307  29713.695   
78             21.1292               80.66               0.563  34618.760   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
329          90.7               7.320                7.460            7.275   
371         173.5               9.310                9.525            9.320   
219         165.9               8.175                8.375            8.315   
403         169.5               9.125                9.310            9.060   
78          127.2               7.330                7.500            7.450   

     Producer_rating  Critic_rating  Trailer_views  Time_taken  \
329            7.515           8.62         483051  111.040000   
371            9.505           7.96         454281  196.000000   
219            8.405           8.72         451935  123.200000   
403            9.100           6.96         384237  157.391498   
78             7.690           8.26         447528  176.480000   

     Twitter_hastags  Avg_age_actors  Num_multiplex  Collection  \
329          283.616              53            452       45200   
371          268.000              25            609      100000   
219          263.680              21            561       46000   
403          301.328              40            677       16600   
78           303.392              53            377       42400   

     3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
329                 0             1            0               0  
371                 1             1            0               0  
219                 1             1            0               0  
403                 1             0            0               1  
78                  1             0            1               0

In [24]:
X_test.shape

(102, 20)

# Standardising Data

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
sc = StandardScaler().fit(X_train)

In [27]:
X_train_std = sc.transform(X_train)

In [28]:
X_test_std = sc.transform(X_test)

In [29]:
X_test_std

array([[-0.40835869, -1.12872913,  0.83336883, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [ 0.71925111,  0.9988844 , -0.65283979, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40257488,  0.39610829,  0.05115377, ...,  1.50268577,
        -0.48525664, -0.75225758],
       ...,
       [-0.3982601 , -0.85812418,  0.89420778, ..., -0.66547513,
        -0.48525664,  1.3293319 ],
       [-0.39934279, -0.07637654,  0.58132175, ...,  1.50268577,
        -0.48525664, -0.75225758],
       [-0.40088071, -0.36702631,  0.31189212, ..., -0.66547513,
        -0.48525664, -0.75225758]])

In [30]:
X_test

Marketing expense  Production expense  Multiplex coverage     Budget  \
329            21.3448               61.48               0.540  35179.815   
371           204.6460               91.20               0.369  34529.880   
219            22.2850               82.78               0.450  35402.015   
403           516.0340               91.20               0.307  29713.695   
78             21.1292               80.66               0.563  34618.760   
..                 ...                 ...                 ...        ...   
56             20.4110               56.48               0.590  35457.565   
455           115.0474               91.20               0.287  36246.375   
60             22.9864               65.26               0.547  31891.255   
213            22.8104               76.18               0.511  35413.125   
108            22.5604               72.12               0.480  35963.070   

     Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
329          90.7               7.320                7.460            7.275   
371         173.5               9.310                9.525            9.320   
219         165.9               8.175                8.375            8.315   
403         169.5               9.125                9.310            9.060   
78          127.2               7.330                7.500            7.450   
..            ...                 ...                  ...              ...   
56          109.2               5.340                5.535            5.285   
455         160.0               8.695                8.790            8.630   
60          139.7               6.335                6.420            6.235   
213         105.8               7.945                8.040            7.910   
108         170.6               8.640                8.910            8.730   

     Producer_rating  Critic_rating  Trailer_views  Time_taken  \
329            7.515           8.62         483051  111.040000   
371            9.505           7.96         454281  196.000000   
219            8.405           8.72         451935  123.200000   
403            9.100           6.96         384237  157.391498   
78             7.690           8.26         447528  176.480000   
..               ...            ...            ...         ...   
56             5.465           8.54         539589  115.880000   
455            9.015           6.96         408819  155.640000   
60             6.560           7.06         465689  157.391498   
213            8.215           7.28         504226  151.240000   
108            8.850           7.82         473768  171.920000   

     Twitter_hastags  Avg_age_actors  Num_multiplex  Collection  \
329          283.616              53            452       45200   
371          268.000              25            609      100000   
219          263.680              21            561       46000   
403          301.328              40            677       16600   
78           303.392              53            377       42400   
..               ...             ...            ...         ...   
56           303.952              22            383       49400   
455          282.256              36            620       28200   
60           222.992              30            439       37400   
213          204.496               3            441       56200   
108          203.168              48            502       39600   

     3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
329                 0             1            0               0  
371                 1             1            0               0  
219                 1             1            0               0  
403                 1             0            0               1  
78                  1             0            1               0  
..                ...           ...          ...             ...  
56                  1             0            1               0

# Training Classification Tree

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html

In [31]:
from sklearn import svm


In [32]:
clf_svm1 = svm.SVC(kernel="linear" , C=0.01)
clf_svm1.fit(X_train_std , y_train)

SVC(C=0.01, kernel='linear')

In [33]:
y_test_pred = clf_svm1.predict(X_test_std)
y_train_pred = clf_svm1.predict(X_train_std)

In [34]:
y_test_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [35]:
from sklearn.metrics import confusion_matrix ,  accuracy_score

In [36]:
confusion_matrix(y_test , y_test_pred)

array([[11, 33],
       [ 5, 53]], dtype=int64)

In [37]:
accuracy_score(y_train , y_train_pred)

0.6064356435643564

In [38]:
accuracy_score(y_test , y_test_pred)

0.6274509803921569

In [39]:
clf_svm1.n_support_

array([186, 189])

#  Grid Search CV

In [40]:
from sklearn.model_selection import GridSearchCV

In [41]:
params = {"C" : (0.001 , 0.005 , 0.01 , 0.05 , 0.1 , 0.5 , 1 ,5 ,10 ,50 ,100 ,500 ,1000)}

In [42]:
clf_svm1=svm.SVC(kernel="linear")

In [43]:
svm_grid_lin=GridSearchCV(clf_svm1,params,n_jobs=-1,cv=10,verbose=1,scoring="accuracy")

In [44]:
svm_grid_lin.fit(X_train_std , y_train)

Fitting 10 folds for each of 13 candidates, totalling 130 fits


GridSearchCV(cv=10, estimator=SVC(kernel='linear'), n_jobs=-1,
             param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50,
                               100, 500, 1000)},
             scoring='accuracy', verbose=1)

In [45]:
svm_grid_lin.best_params_

{'C': 0.1}

In [46]:
linsvm_clf = svm_grid_lin.best_estimator_

In [47]:
accuracy_score(y_test , linsvm_clf.predict(X_test))

0.43137254901960786

#  Polynomial

In [48]:
clf_svm_p3 = svm.SVC(kernel="poly" , degree=2 , C=0.1)
clf_svm_p3.fit(X_train_std , y_train)

SVC(C=0.1, degree=2, kernel='poly')

In [49]:
y_train_pred = clf_svm_p3.predict(X_train_std)
y_test_pred = clf_svm_p3.predict(X_test_std)

In [50]:
accuracy_score(y_test , y_test_pred)

0.5588235294117647

In [51]:
clf_svm_p3.n_support_

array([185, 194])

# Radial

In [52]:
clf_svm_r = svm.SVC(kernel="rbf" , gamma=0.5 , C=10)
clf_svm_r.fit(X_train_std , y_train)

SVC(C=10, gamma=0.5)

In [53]:
y_train_pred = clf_svm_r.predict(X_train_std)
y_test_pred = clf_svm_r.predict(X_test_std)

In [54]:
accuracy_score(y_test , y_test_pred)

0.6176470588235294

# Radial Grid

In [55]:
params = { "C": (0.01 , 0.05 , 0.1 , 0.5 , 1 , 5 , 10 , 50) , 
            "gamma" : (0.001 , 0.01 , 0.1 , 0.5 , 1)}

In [56]:
clf_svm_r=svm.SVC(kernel="rbf")

In [57]:
svm_grid_rad=GridSearchCV(clf_svm_r , params , n_jobs=-1, cv=3 , verbose=1 , scoring="accuracy")

In [58]:
svm_grid_rad.fit(X_train_std , y_train)

Fitting 3 folds for each of 40 candidates, totalling 120 fits


GridSearchCV(cv=3, estimator=SVC(), n_jobs=-1,
             param_grid={'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
                         'gamma': (0.001, 0.01, 0.1, 0.5, 1)},
             scoring='accuracy', verbose=1)

In [59]:
svm_grid_rad.best_params_

{'C': 50, 'gamma': 0.001}

In [60]:
radsvm_clf=svm_grid_rad.best_estimator_

In [61]:
accuracy_score(y_test , radsvm_clf.predict(X_test_std))

0.6176470588235294